PersonalBlog/Models/FindUserViewModel.cs
namespace PersonalBlog.Models
{
    public class FindUserViewModel
    {
        public string loginPart { get; set; }
    }
}

PersonalBlog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PersonalBlog.BLL.DTO;
using PersonalBlog.BLL.Interfaces;
using PersonalBlog.DAL.Entities;
using PersonalBlog.DAL.Identity;
using PersonalBlog.Models;

namespace PersonalBlog.Controllers
{
    public class BlogController : Controller
    {
        /// <summary>
        /// Post service
        /// </summary>
        private IPostService _postService;
        
        /// <summary>
        /// Comment service
        /// </summary>
        private ICommentService _commentService;

        /// <summary>
        /// User manager
        /// </summary>
        private ApplicationUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
        }

        /// <summary>
        /// Reload all Session Data
        /// </summary>
        public void Datareload()
        {
            Session.Clear();
            TempData.Clear();
            var userId = User.Identity.GetUserId();
            var user = UserManager.Users.FirstOrDefault(w => w.Id == userId);
            Session["UserLogin"] = user.Login;
            Session["UserName"] = user.FirstName;
        }

        /// <summary>
        /// Constructor that make DI
        /// </summary>
        /// <param name="service">Post service</param>
        /// <param name="commentService">Comment service</param>
        public BlogController(IPostService service, ICommentService commentService)
        {
            _postService = service;
            _commentService = commentService;
        }

        /// <summary>
        /// Main page of blog
        /// </summary>
        /// <param name="findText">text to search in all posts</param>
        /// <returns>View of main blog</returns>
        [Authorize]
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Index(FindtextViewModel findText)
        {
            Datareload();

            if (string.IsNullOrEmpty(findText.Text))
            {
                findText.Text = "";
            }

            var curUser = User.Identity.GetUserId();
            findText.isAdmin = UserManager.Users.SingleOrDefault(w => w.Id == curUser)?.Role == "Admin";

            IEnumerable<PostDTO> phoneDtos = _postService.GetPosts();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<PostDTO, Post>()).CreateMapper();
            var phones = mapper.Map<IEnumerable<PostDTO>, List<Post>>(phoneDtos);
            TempData["AllPosts"] = phones;
            TempData["Comments"] = _commentService.GetComments();
            return View(findText);
        }

        /// <summary>
        /// Page of personal blog of user
        /// </summary>
        /// <param name="login">Login of user that page will shows</param>
        /// <returns>User's personal blog</returns>
        /// <exception cref="Exception">Don't found user</exception>
        [Authorize]
        public ActionResult PersonalBlog(string login)
        {
            try
            {
                if (string.IsNullOrEmpty((string) Session["UserLogin"]))
                {
                    Datareload();
                }

                IEnumerable<PostDTO> postsDtos = _postService.GetPosts();
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<PostDTO, Post>()).CreateMapper();
                var posts = mapper.Map<IEnumerable<PostDTO>, List<Post>>(postsDtos);
                TempData.Clear();
                TempData["Posts"] = posts;

                var postModel = new PostViewModel();
                if (string.IsNullOrEmpty(login))
                {
                    TempData["UserId"] = Guid.Parse(User.Identity.GetUserId());
                    postModel.IsMe = true;
                }
                else
                {
                    var curId = User.Identity.GetUserId();
                    var userId = UserManager.Users.FirstOrDefault(w => w.Login == login)?.Id;
                    var selectedId = UserManager.Users.SingleOrDefault(w => w.Id == curId)?.Id;
                    if (!string.IsNullOrEmpty(userId))
                    {
                        TempData["UserId"] = Guid.Parse(userId);
                        if (userId == selectedId)
                        {
                            postModel.IsMe = true;
                        }
                    }
                    else
                    {
                        throw new Exception("404");
                        // return RedirectToAction("FindUsers");
                    }
                }

                var curUserId = User.Identity.GetUserId();
                TempData["User"] = UserManager.Users.FirstOrDefault(w => w.Id == curUserId);
                TempData["Comments"] = _commentService.GetComments();
                return View(postModel);
            }
            catch
            {
                return View("Error");
            }
        }

        /// <summary>
        /// Page with user data and changing it
        /// </summary>
        /// <returns>Settings view</returns>
        [Authorize]
        public ActionResult UserSettings()
        {
            var userId = User.Identity.GetUserId();
            var user = UserManager.Users.FirstOrDefault(w => w.Id == userId);

            TempData["FirstName"] = user.FirstName;
            TempData["LastName"] = user.LastName;
            TempData["Birthdate"] = user.Birthdate;
            TempData["City"] = user.City;
            TempData["Languages"] = user.Languages;
            TempData["About"] = user.About;
            TempData["Email"] = user.Email;
            TempData["Phone"] = user.PhoneNumber;
            return View();
        }

        /// <summary>
        /// Try to change user Data
        /// </summary>
        /// <param name="model"></param>
        /// <returns>Changing user data or exception</returns>
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> ChangeUserData(UserViewModel model)
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

            string exception = "";
            if (string.IsNullOrEmpty(model.FirstName))
            {
                exception += "<p>Wrong user name</p>";
            }
            if (string.IsNullOrEmpty(model.LastName))
            {
                exception += "<p>Wrong user last name</p>";
            }
            if (model.BirthDate == default(DateTime) || model.BirthDate > DateTime.UtcNow)
            {
                exception += "<p>Wrong birthdate</p>";
            }
            // if (string.IsNullOrEmpty(UserManager.PasswordHasher.HashPassword(model.Password)))
            // {
            //     exception += "<p>Wrong password</p>";
            // }
            if (string.IsNullOrEmpty(model.Email) || !model.Email.Contains("@"))
            {
                exception += "<p>Wrong email address<p>";
            }
            if (string.IsNullOrEmpty(model.Phone))
            {
                exception += "<p>Wrong phone number</p>";
            }

            if (exception == "")
            {
                user.FirstName = model.FirstName;
                user.LastName = model.LastName; 
                user.City = model.City;
                user.Languages = model.Languages;
                user.About = model.About;
                user.PasswordHash = UserManager.PasswordHasher.HashPassword(model.Password);
                user.Email = model.Email;
                user.Birthdate = model.BirthDate;
                user.PhoneNumber = model.Phone;
                user.UserName = model.Email;
                
                await UserManager.UpdateAsync(user);
            }

            return RedirectToAction("UserSettings");
        }

        /// <summary>
        /// Creating post
        /// </summary>
        /// <param name="model">Model from view</param>
        /// <returns>Creating post or exception</returns>
        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CreatePost(PostViewModel model)
        {
            if (string.IsNullOrEmpty((string) Session["UserLogin"]))
            {
                Datareload();
            }

            if (!string.IsNullOrEmpty(model.PostText))
            {
                if (string.IsNullOrEmpty(model.TagsText))
                {
                    _postService.MakePost(Guid.Parse(User.Identity.GetUserId()), model.PostText, "",
                        Convert.ToString(Session["UserLogin"]));
                }
                else
                {
                    _postService.MakePost(Guid.Parse(User.Identity.GetUserId()), model.PostText, model.TagsText,
                        Convert.ToString(Session["UserLogin"]));
                }
            }
            else
            {
                TempData["NullInputException"] = "1";
            }

            return RedirectToAction("PersonalBlog");
        }

        /// <summary>
        /// Show comments of post
        /// </summary>
        /// <param name="postId">Id of post</param>
        /// <returns>View of list comments of selected post</returns>
        [Authorize]
        public ActionResult PostComments(int? postId)
        {
            Datareload();
            
            var post = _postService.GetPosts().SingleOrDefault(w => w.Id == postId);
            if (post == null)
            {
                return View("Error");
            }
            
            IEnumerable<CommentDTO> commentDtos = _commentService.GetComments();
            var mapper2 = new MapperConfiguration(cfg => cfg.CreateMap<CommentDTO, Comment>()).CreateMapper();
            var comments = mapper2.Map<IEnumerable<CommentDTO>, List<Comment>>(commentDtos);

PersonalBlog/Views/Blog/EditPost.cshtml
@model PersonalBlog.Models.PostViewModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/materialize.css">
    <script src="~/Scripts/materialize.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/Chips.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit post</title>
</head>
<body>
<div class="clear-30"></div>
<div class="row container">
    <div class="clear-15"></div>
    <div class="col s12 z-depth-2 deep-purple lighten-4">
        <h4 class="center">Change your post</h4>
        @using (Html.BeginForm("ChangePostData", "Blog", FormMethod.Post))
        {
            <div class="input-field col s12">
                @Html.TextAreaFor(m => m.PostText, new {@class = "materialize-textarea", @data_length = "800", @id = "textarea", @Value = Session["EditPostId"]})
            </div>
            <button type="submit" value="Create" class="green btn .light-green.accent-3 right">
                Apply
            </button>
        }
    </div>
</div>
</body>
</html>

PersonalBlog/Views/Blog/FindUsers.cshtml
@using PersonalBlog.DAL.Entities
@using PersonalBlog.DAL.Identity
@using PersonalBlog.Helpers
@model string

@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/materialize.css">
    <script src="~/Scripts/materialize.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Find Peoples</title>
</head>
<body>
<div class="clear-30"></div>
<div class="row container">
    <div class="col s12">
        <div class="col m8 offset-m2 s12 z-depth-2 deep-purple lighten-4">
            <h4>What's new?</h4>
            <form method="get" action="../Blog/FindUsers">
                <div class="input-field col s12">
                    <input placeholder="Enter someone login" name="loginPart" id="login" type="text" class="validate">
                    <label for="login">Login</label>
                </div>
                <button type="submit" value="Create" class="green btn .light-green.accent-3 right">
                    Find
                </button>
            </form>
            <div class="clear-10"></div>
        </div>
    </div>
    @Html.FindUsers((List<ApplicationUser>) TempData["Users"], Model, x => Url.Action("PersonalBlog", new {login = x}))
</div>
<script src="~/Scripts/ReadMore.js"></script>
</body>
</html>

PersonalBlog/Views/Blog/Index.cshtml
@using PersonalBlog.BLL.DTO
@using PersonalBlog.DAL.Entities
@using PersonalBlog.Helpers
@model PersonalBlog.Models.FindtextViewModel

@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <link href="~/Content/Materials.css" rel="stylesheet">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/materialize.css">
    <script src="~/Scripts/materialize.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog page</title>
</head>
<body>
<br>
<div class="row container">
    <div class="clear-15"></div>
    <div class="col s12 z-depth-2 deep-purple lighten-4">
        <h4>Find blog by text or tag</h4>
        @using (Html.BeginForm("Index", "Blog", FormMethod.Get))
        {
            <div class="input-field col s12">
                @Html.EditorFor(m => m.Text, new {@class = "lightLabel validate right", @id = "textInp"})
            </div>
            <button type="submit" value="Create" class="green btn .light-green.accent-3 right">
                Find
            </button>
        }
    </div>
</div>
<div class="row container">
    @using (Html.BeginForm())
    {
        @Html.PostGenerator((List<Post>) TempData["AllPosts"], x => Url.Action("PostComments", new {postId = x}), x => Url.Action("EditPost", new {postId = x}),x => Url.Action("PersonalBlog", new {login = x}) , (IEnumerable<CommentDTO>) TempData["Comments"], Model.Text, Model.isAdmin)
    }
</div>
<script src="~/Scripts/ReadMore.js"></script>
<script src="~/Scripts/imgLikeChanger.js"></script>
<script >
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.dropdown-trigger');
    var instances = M.Dropdown.init(elems);
  });
</script>
</body>
</html>

PersonalBlog/Views/Blog/PersonalBlog.cshtml
@using PersonalBlog.BLL.DTO
@using PersonalBlog.DAL.Entities
@using PersonalBlog.DAL.Identity
@using PersonalBlog.Helpers
@using PersonalBlog.Models
@model PersonalBlog.Models.PostViewModel

@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/materialize.css">
    <script src="~/Scripts/materialize.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/Chips.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Blog</title>
</head>
<body>
<div class="clear-30"></div>
<div class="row container">
    @Html.UserData((ApplicationUser) TempData["User"])
    <div class="clear-15"></div>
    @if (Model.IsMe)
    {
        <div class="col s12 z-depth-2 deep-purple lighten-4">

            <h4 class="center">What's new?</h4>
            @using (Html.BeginForm("CreatePost", "Blog", FormMethod.Post))
            {
            <div class="input-field col s12">
                @Html.TextAreaFor(m => m.PostText, new {@class = "materialize-textarea", @data_length = "800", @id = "textarea"})
            </div>
            <div class="col m8 offset-m2 s12 z-depth-2 deep-purple lighten-4">

                @if ((string) TempData["NullInputException"] == "1")
                {
                    <p style="color: red">Empty field</p>
                }
                <input type="text" id="tagInp1">
                <div class="chips"></div>
                <button type="submit" value="Create" class="green btn .light-green.accent-3 right">
                    Send
                </button>

                <div class="clear-10"></div>
            </div>
            }
        </div>
    }
    @using (Html.BeginForm())
    {
        @Html.MyPostsGenerator((List<Post>) TempData["Posts"], Guid.Parse(Convert.ToString(TempData["UserId"])), x => Url.Action("EditPost", new {postId = x}),
            x => Url.Action("PostComments", new {postId = x}), (IEnumerable<CommentDTO>)TempData["Comments"], Model.IsMe)
    }

</div>
<script >
    $("#tagInp1").attr("type", "hidden")
    $("#tagInp1").attr("name", "TagsText")
</script>
<script >
    M.AutoInit();
</script>
<script src="~/Scripts/ReadMore.js"></script>
</body>
</html>

PersonalBlog/Views/Blog/PostComments.cshtml
@using PersonalBlog.BLL.DTO
@using PersonalBlog.DAL.Entities
@using PersonalBlog.Helpers
@model PersonalBlog.Models.UserViewModel

@{
    Layout = "../../Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/materialize.css">
    <script src="~/Scripts/materialize.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="row container">
    <div class="col s12">
        <div class="col m8 offset-m2 s12 z-depth-2 deep-purple lighten-4">
            @using (Html.BeginForm("LeaveComment", "Blog"))
            {
                <div class="input-field col s12">
                    <input required placeholder="Enter comment text" name="commentText" id="comment" type="text" class="validate">
                    <label for="comment">Comment</label>
                </div>
                <button type="submit" value="Create" class="green btn .light-green.accent-3 center">
                    Leave a comment
                </button>
            }
            <div class="clear-10"></div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.PostCommentGenerator((IEnumerable<Comment>) TempData["Comments"], x => Url.Action("DeleteComment", new {commentId = x}), Model)
    }
</div>
</body>

</html>

PersonalBlog/Views/Blog/UserSettings.cshtml
@model PersonalBlog.Models.UserViewModel

@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!doctype html>
<html lang="en">
<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <link rel="stylesheet" href="~/Content/materialize.css">
    <script src="~/Scripts/materialize.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Find Peoples</title>
</head>
<body>
<div class="clear-30"></div>
<div class="row container">
    <div class="col s12">
        <div class="col m8 offset-m2 s12 z-depth-2 purple darken-4">
            <div class="lid">
                @using (Html.BeginForm("ChangeUserData", "Blog"))
                {
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.FirstName, "First Name", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.FirstName, new {htmlAttributes = new {@type = "text", @class = "lightLabel validate", @Value = TempData["FirstName"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.LastName, "Last Name", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.LastName, new {htmlAttributes = new {@class = "lightLabel validate", @Value = TempData["LastName"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.EditorFor(model => model.BirthDate, new {htmlAttributes = new {@type = "date", @class = "lightLabel validate", @Value = TempData["Birthdate"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.City, "City", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.City, new {htmlAttributes = new {@class = "lightLabel validate", @Value = TempData["City"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.Languages, "Languages you speak", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.Languages, new {htmlAttributes = new {@class = "lightLabel validate", @Value = TempData["Languages"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.About, "Information about you", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.About, new {htmlAttributes = new {@class = "lightLabel validate", @Value = TempData["About"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.Password, "Password", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.Password, new {htmlAttributes = new {@class = "lightLabel validate"}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.PasswordConfirm, "Confirm password", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.PasswordConfirm, new {htmlAttributes = new {@class = "lightLabel validate", @placeholder = "********"}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.Email, "EMail address", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "lightLabel validate", @Value = TempData["Email"]}})
                    </div>
                    <div class="input-field col s12">
                        @Html.LabelFor(model => model.Phone, "Phone number", htmlAttributes: new {@class = "lightLabel"})
                        @Html.EditorFor(model => model.Phone, new {htmlAttributes = new {@class = "lightLabel validate", @Value = TempData["Phone"]}})
                    </div>
                    <div class="input-field col s12">
                        <button type="submit" value="Create" class="right green btn .light-green.accent-3 waves-effect waves-light">
                            Apply
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/ReadMore.js"></script>
</body>
</html>